export const API_ROUTES = {
  health: () => '/health',
  auth: {
    login: () => '/auth/login',
    getTokenForRegistration: () => '/auth/get-token-for-registration',
    register: () => '/auth/register',
    resendVerificationCode: () => '/auth/resend-verification-code',
    logout: () => '/auth/logout',
    refreshTokens: () => '/auth/refresh',
    changePassword: () => '/auth/change-password',
    getResetPasswordToken: () => '/auth/get-reset-password-token',
    resendResetPasswordCode: () => '/auth/resend-reset-password-verification-code',
    verifyResetPasswordCode: () => '/auth/verify-reset-password-code',
    setNewPassword: () => '/auth/set-new-password',
  },
  users: {
    me: () => '/users/me',
    updateCurrentUser: () => '/users/update',
    deleteAccount: () => '/users/delete-account',
  },
  projects: {
    list: () => `/projects/list`,
    get: (id: string) => `/projects/get/${id}`,
    create: () => 'projects/create',
    update: (id: string) => `/projects/update/${id}`,
    delete: (id: string) => `/projects/delete?id=${id}`,
    generateInvitationLink: () => '/projects/invitation-link',
    joinToProject: () => '/projects/join-to-project',
    saveChanges: () => '/projects/update-project-data',
    getProjectData: () => '/projects/project-data',
    getMembers: (id: string) => `/projects/${id}/members`,
    deleteMember: (id: string, memberId: string) => `/projects/${id}/members/delete/${memberId}`,
  },
  notes: {
    list: () => `/notes/list`,
    create: () => 'notes/create',
    delete: (id: string) => `/notes/delete/${id}`,
    update: (id: string) => `/notes/update/${id}`,
  },
};
