name: Build and Deploy to VPS

on:
  push:
    branches: [ staging ] # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Use the Node.js version your app requires

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Create tarball
        run: |
          tar -czvf dist.tar.gz -C dist .

      - name: Upload tarball to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "dist.tar.gz"
          target: ${{ secrets.TARGET_PATH }}
          rm: true

      - name: Unpack tarball on VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/deploy
            . graphitsql-frontend-staging.sh
            # cd /path/to/your/app
            # tar -xzvf dist.tar.gz
            # rm dist.tar.gz